### PR TITLE
Fix: Unzip the right file

### PR DESCRIPTION
**Pull request by Ghost---Shadow**

### CODE REVIEW

**Comment by Ghost---Shadow** [comment]
@dwmkerr Lets wait for the pipeline to pass before merging. :P

**Comment by dwmkerr** [comment]
Yeah I didn't realise you'd only just pushed, running locally and have applied the same fix 😄

**Comment by dwmkerr** [comment]
I've just updated CircleCI to build forked PRs, you can push a commit again and that should trigger a rebuilt. You might need to update the tests file to update the version of terraform it checks for, that'll trigger a rebuild

**Comment by Ghost---Shadow** [comment]
I made the edits in browser :P 
Looks like no pipeline is running. Did you run out of credits?

**Comment by dwmkerr** [comment]
I _think_ if you make an edit now it'll build - I just updated the circleci config to allow builds from pull requests (before that it would only build branches in the repo itself). Try updating the version numbers in `tests.sh` to trigger a built

**Comment by dwmkerr** [comment]
At least I can see the test is working locally:

image

**Comment by dwmkerr** [comment]
Fixed in #11, released as v0.3.1

**Comment by Ghost---Shadow** [comment]
The image name `dwmkerr/terraform-ci` does not work for local testing.
Also added that as a parameter

**Comment by dwmkerr** [comment]
👍

**Pull request merged**
